<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Antarctic Basin SVG Overlays Test</title>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: 'Inter', sans-serif;
        }
        .map-container {
            position: relative;
            width: 1500px;
            height: 1500px;
            margin: 20px auto;
            border: 1px solid #ccc;
            box-shadow: 0 8px 16px rgba(0,0,0,0.2);
            background-color: #fff;
        }
        .map-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 1500px;
            height: 1500px;
            z-index: 1;
        }
        .overlay-svg {
            position: absolute;
            top: 0;
            left: 0;
            width: 1500px;
            height: 1500px;
            z-index: 2;
            pointer-events: none; /* Let clicks pass through empty space of the SVG viewBox */
        }
        /* Make the polygons interactable and style the hover effects */
        .overlay-svg polygon {
            pointer-events: all; /* Restore pointer events on the actual polygon shapes */
            fill: rgba(0, 0, 0, 0) !important; /* Transparent fill to catch hover events */
            transition: fill 0.2s ease-in-out, stroke-width 0.2s ease-in-out, stroke 0.2s;
        }
        .overlay-svg polygon:hover {
            fill: rgba(255, 0, 0, 0.4) !important;
            stroke: #ffff00 !important;
            stroke-width: 6 !important;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center;">Antarctic Basin Selection Overlays Test</h1>
    <p style="text-align: center;">Hover over the basins on the map to see the interactive SVG polygons.</p>

    <div class="map-container">
        <!-- Base Map Image -->
        <img class="map-image" src="CPOM-AIS-L3C-DHDT-MULTIMISSION-5KM-199505-202601-fv1-sec.webp" alt="Antarctica SEC Map">
        
        <!-- Injecting the SVGs dynamically using PHP -->
        <?php
        $svg_dir = '../polygons/antarctica/output_svgs/';
        
        for ($i = 1; $i <= 18; $i++) {
            $svg_file = $svg_dir . 'rignot2016_basin' . $i . '_overlay.svg';
            if (file_exists($svg_file)) {
                $svg_content = file_get_contents($svg_file);
                
                // Add the class overlay-svg and a data-basin attribute to the <svg> root element
                $svg_content = str_replace('<svg ', '<svg class="overlay-svg" data-basin="' . $i . '" ', $svg_content);
                
                echo $svg_content;
            }
        }
        ?>
    </div>

    <script>
        document.querySelectorAll('.overlay-svg polygon').forEach(function(polygon) {
            polygon.addEventListener('click', function(e) {
                // The <svg> container has the data-basin attribute
                const svg = e.target.closest('svg');
                if (svg) {
                    const basinId = svg.getAttribute('data-basin');
                    console.log("Clicked Basin " + basinId + "!");
                    
                    // Fetch the JSON timeseries data generated by process_timeseries.py
                    fetch('data/timeseries/basin_' + basinId + '.json')
                        .then(response => response.json())
                        .then(data => {
                            console.log("Loaded data for Basin " + basinId + ":");
                            console.table(data.slice(0, 5)); // print first 5 records to console
                            console.log("... and " + (data.length - 5) + " more records.");
                            alert("Basin " + basinId + " clicked! Loaded " + data.length + " timeseries records. Check browser console for data.");
                        })
                        .catch(error => {
                            console.error('Error loading timeseries for Basin ' + basinId + ':', error);
                            alert("Failed to load data for Basin " + basinId);
                        });
                }
            });
        });
    </script>
</body>
</html>
